import 'package:meta/meta.dart';

/// GDPR Article 30 / CCPA data processing compliance report.
///
/// Auto-generated by [Tracelet.generateComplianceReport], this provides a
/// structured report of all location data processing: what was collected,
/// stored, synced, how long it's retained, privacy measures active, and
/// audit trail status.
@immutable
class ComplianceReport {
  /// Creates a new [ComplianceReport].
  const ComplianceReport({
    required this.generatedAt,
    required this.totalLocationsStored,
    required this.totalLocationsSynced,
    required this.maxDaysToPersist,
    required this.maxRecordsToPersist,
    this.oldestRecord,
    this.newestRecord,
    required this.databaseEncrypted,
    required this.activePrivacyZones,
    required this.privacyZoneIdentifiers,
    this.httpSyncUrl,
    required this.autoSyncEnabled,
    required this.auditTrailEnabled,
    this.auditTrailValid,
    required this.locationPermissionStatus,
    required this.motionPermissionStatus,
    required this.sparseUpdatesEnabled,
    required this.kalmanFilterEnabled,
    required this.deltaCompressionEnabled,
    required this.trackingEnabled,
    required this.trackingMode,
  });

  /// Report generation timestamp.
  final DateTime generatedAt;

  /// Total locations currently stored in the local database.
  final int totalLocationsStored;

  /// Total locations that have been synced to the server (approximate).
  final int totalLocationsSynced;

  /// Configured maximum days to retain records (-1 = unlimited).
  final int maxDaysToPersist;

  /// Configured maximum records to retain (-1 = unlimited).
  final int maxRecordsToPersist;

  /// Timestamp of the oldest record in the database.
  final String? oldestRecord;

  /// Timestamp of the newest record in the database.
  final String? newestRecord;

  /// Whether the database is encrypted at rest.
  final bool databaseEncrypted;

  /// Number of active privacy zones.
  final int activePrivacyZones;

  /// Identifiers of all active privacy zones.
  final List<String> privacyZoneIdentifiers;

  /// HTTP sync destination URL (null if disabled).
  final String? httpSyncUrl;

  /// Whether auto-sync is enabled.
  final bool autoSyncEnabled;

  /// Whether audit trail is enabled.
  final bool auditTrailEnabled;

  /// Whether the audit trail chain is valid (null if not verified).
  final bool? auditTrailValid;

  /// Current location permission status code.
  final int locationPermissionStatus;

  /// Current motion/activity permission status code.
  final int motionPermissionStatus;

  /// Whether sparse updates are enabled.
  final bool sparseUpdatesEnabled;

  /// Whether Kalman filter is enabled.
  final bool kalmanFilterEnabled;

  /// Whether delta compression is enabled.
  final bool deltaCompressionEnabled;

  /// Whether tracking is currently enabled.
  final bool trackingEnabled;

  /// Current tracking mode name.
  final String trackingMode;

  /// Export as JSON for automated compliance tooling.
  Map<String, Object?> toJson() {
    return <String, Object?>{
      'generatedAt': generatedAt.toIso8601String(),
      'dataInventory': <String, Object?>{
        'totalLocationsStored': totalLocationsStored,
        'totalLocationsSynced': totalLocationsSynced,
        'oldestRecord': oldestRecord,
        'newestRecord': newestRecord,
      },
      'retentionPolicy': <String, Object?>{
        'maxDaysToPersist': maxDaysToPersist,
        'maxRecordsToPersist': maxRecordsToPersist,
      },
      'privacyMeasures': <String, Object?>{
        'databaseEncrypted': databaseEncrypted,
        'activePrivacyZones': activePrivacyZones,
        'privacyZoneIdentifiers': privacyZoneIdentifiers,
        'sparseUpdatesEnabled': sparseUpdatesEnabled,
        'kalmanFilterEnabled': kalmanFilterEnabled,
        'deltaCompressionEnabled': deltaCompressionEnabled,
      },
      'dataDestinations': <String, Object?>{
        'httpSyncUrl': httpSyncUrl,
        'autoSyncEnabled': autoSyncEnabled,
      },
      'auditTrail': <String, Object?>{
        'enabled': auditTrailEnabled,
        'valid': auditTrailValid,
      },
      'consent': <String, Object?>{
        'locationPermissionStatus': locationPermissionStatus,
        'motionPermissionStatus': motionPermissionStatus,
      },
      'trackingState': <String, Object?>{
        'enabled': trackingEnabled,
        'mode': trackingMode,
      },
    };
  }

  /// Export as human-readable Markdown report.
  String toMarkdown() {
    final buf = StringBuffer()
      ..writeln('# Tracelet Compliance Report')
      ..writeln()
      ..writeln('Generated: ${generatedAt.toIso8601String()}')
      ..writeln()
      ..writeln('## Data Inventory')
      ..writeln()
      ..writeln('| Metric | Value |')
      ..writeln('|--------|-------|')
      ..writeln('| Locations stored | $totalLocationsStored |')
      ..writeln('| Locations synced | $totalLocationsSynced |')
      ..writeln('| Oldest record | ${oldestRecord ?? "N/A"} |')
      ..writeln('| Newest record | ${newestRecord ?? "N/A"} |')
      ..writeln()
      ..writeln('## Retention Policy')
      ..writeln()
      ..writeln(
        '- Max days to persist: '
        '${maxDaysToPersist == -1 ? "Unlimited" : "$maxDaysToPersist days"}',
      )
      ..writeln(
        '- Max records to persist: '
        '${maxRecordsToPersist == -1 ? "Unlimited" : "$maxRecordsToPersist"}',
      )
      ..writeln()
      ..writeln('## Privacy Measures')
      ..writeln()
      ..writeln(
        '- Database encryption: ${databaseEncrypted ? "Enabled" : "Disabled"}',
      )
      ..writeln('- Active privacy zones: $activePrivacyZones')
      ..writeln(
        '- Sparse updates: ${sparseUpdatesEnabled ? "Enabled" : "Disabled"}',
      )
      ..writeln(
        '- Kalman filter: ${kalmanFilterEnabled ? "Enabled" : "Disabled"}',
      )
      ..writeln(
        '- Delta compression: '
        '${deltaCompressionEnabled ? "Enabled" : "Disabled"}',
      )
      ..writeln()
      ..writeln('## Data Destinations')
      ..writeln()
      ..writeln('- HTTP sync URL: ${httpSyncUrl ?? "Not configured"}')
      ..writeln('- Auto sync: ${autoSyncEnabled ? "Enabled" : "Disabled"}')
      ..writeln()
      ..writeln('## Audit Trail')
      ..writeln()
      ..writeln('- Enabled: ${auditTrailEnabled ? "Yes" : "No"}')
      ..writeln(
        '- Chain valid: '
        '${auditTrailValid == null
            ? "Not verified"
            : auditTrailValid!
            ? "Yes"
            : "No"}',
      )
      ..writeln()
      ..writeln('## Consent Status')
      ..writeln()
      ..writeln('- Location permission: $locationPermissionStatus')
      ..writeln('- Motion permission: $motionPermissionStatus')
      ..writeln()
      ..writeln('## Tracking State')
      ..writeln()
      ..writeln('- Enabled: ${trackingEnabled ? "Yes" : "No"}')
      ..writeln('- Mode: $trackingMode');

    return buf.toString();
  }

  @override
  String toString() =>
      'ComplianceReport(generatedAt: $generatedAt, '
      'locationsStored: $totalLocationsStored, '
      'privacyZones: $activePrivacyZones, '
      'auditTrail: $auditTrailEnabled)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComplianceReport &&
          runtimeType == other.runtimeType &&
          generatedAt == other.generatedAt &&
          totalLocationsStored == other.totalLocationsStored;

  @override
  int get hashCode => Object.hash(generatedAt, totalLocationsStored);
}
