package com.ikolvi.tracelet.example

import android.util.Base64
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

class MainActivity : FlutterActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        
        // Register a safe, non-conflicting debug channel for the parity check
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "com.tracelet/debug")
            .setMethodCallHandler { call, result ->
                if (call.method == "debugVerifyRustParity") {
                    try {
                        // Dynamically load the classes generated by UniFFI
                        val geoClass = Class.forName("uniffi.tracelet_core.GeoConfig")
                        val motionClass = Class.forName("uniffi.tracelet_core.MotionConfig")
                        
                        // Extract all compiled fields inside the JVM class definitions
                        val geoFields = geoClass.declaredFields.map { it.name }
                        val motionFields = motionClass.declaredFields.map { it.name }
                        
                        // Expected properties defined in Dart Config models
                        val expectedGeo = listOf(
                            "stopAfterElapsedMinutes", "maxMonitoredGeofences", "periodicLocationInterval",
                            "periodicDesiredAccuracy", "sparseMaxIdleSeconds", "batteryBudgetPerHour",
                            "enableDeadReckoning", "deadReckoningActivationDelay", "deadReckoningMaxDuration",
                            "resolveAddress"
                        )
                        val expectedMotion = listOf(
                            "isMoving", "activityRecognitionInterval", "minimumActivityRecognitionConfidence",
                            "stopDetectionDelay", "stopOnStationary", "stationaryRadius", "useSignificantChangesOnly",
                            "stillThreshold", "stillSampleCount", "motionDetectionMode", "speedMovingThreshold",
                            "speedStationaryDelay", "stationaryTrackingMode", "stationaryPeriodicInterval",
                            "stationaryPeriodicAccuracy", "speedWakeConfirmCount"
                        )
                        
                        // Detect which of these are physically missing in the Rust-compiled UniFFI class
                        val missingGeo = expectedGeo.filter { !geoFields.contains(it) }
                        val missingMotion = expectedMotion.filter { !motionFields.contains(it) }
                        
                        result.success(mapOf(
                            "missingGeo" to missingGeo,
                            "missingMotion" to missingMotion
                        ))
                    } catch (e: ClassNotFoundException) {
                        result.error(
                            "CLASS_NOT_FOUND", 
                            "Tracelet UniFFI classes not found. Is the plugin installed and compiled?", 
                            e.message
                        )
                    } catch (e: Exception) {
                        result.error("REFLECTION_ERROR", e.message, null)
                    }
                } else if (call.method == "debugCrashModelPredict") {
                    // #183: verify the on-device crash-ML chain end-to-end —
                    // AES-256-GCM decrypt of an encrypted forest blob + tree-walk
                    // inference — using the real rebuilt Rust core.
                    try {
                        val blobB64 = call.argument<String>("blob")!!
                        val keyB64 = call.argument<String>("key")!!
                        val features = call.argument<List<Double>>("features")!!
                        val blob = Base64.decode(blobB64, Base64.DEFAULT)
                        val key = Base64.decode(keyB64, Base64.DEFAULT)
                        val model = uniffi.tracelet_core.CrashModel.fromEncrypted(blob, key)
                        result.success(
                            mapOf(
                                "proba" to model.predictProba(features),
                                "treeCount" to model.treeCount().toInt(),
                            ),
                        )
                    } catch (e: Exception) {
                        result.error("CRASH_MODEL_ERROR", e.message, null)
                    }
                } else {
                    result.notImplemented()
                }
            }
    }
}
