include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    sort_child_properties_last: true
    unawaited_futures: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - "build/**"
