name: tracelet_web
description: Web implementation of the Tracelet background geolocation plugin.
version: 3.2.12
topics:
  - location
  - background
  - geofencing
  - web
license: Apache-2.0
homepage: https://github.com/Ikolvi/Tracelet
repository: https://github.com/Ikolvi/Tracelet/tree/main/packages/tracelet_web
funding:
  - https://github.com/sponsors/GalacticTitan
  - https://www.buymeacoffee.com/kiranbjm
  - https://thanks.dev/d/gh/galactictitan/dependencies
  - https://www.patreon.com/c/kiranbjm

resolution: workspace

environment:
  sdk: ^3.10.3
  flutter: ">=3.22.0"

dependencies:
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  tracelet_platform_interface: ^3.2.12
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: tracelet
    platforms:
      web:
        pluginClass: TraceletWebPlugin
        fileName: tracelet_web.dart
