// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../state/battery_budget.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BatteryBudgetEngineDart>>
abstract class BatteryBudgetEngineDart implements RustOpaqueInterface {
  /// Returns the active accuracy index (0 = highest) calculated by the engine.
  int getAccuracyIndex();

  /// Returns the active distance filter (in meters) calculated by the engine.
  double getDistanceFilter();

  /// Returns the current periodic interval (if any) recommended by the engine.
  int? getPeriodicInterval();

  /// Returns the recommended tracking interval based on the latest battery adjustments.
  PlatformInt64 getRecommendedIntervalMs({
    required PlatformInt64 defaultIntervalMs,
  });

  /// Returns true if the device is currently charging.
  bool isCharging();

  /// Creates a new BatteryBudgetEngine.
  factory BatteryBudgetEngineDart({
    required double targetBudgetPerHour,
    required double initialDistanceFilter,
    required int initialAccuracyIndex,
    int? initialPeriodicInterval,
  }) =>
      RustLib.instance.api.crateApiDartBatteryBudgetBatteryBudgetEngineDartNew(
        targetBudgetPerHour: targetBudgetPerHour,
        initialDistanceFilter: initialDistanceFilter,
        initialAccuracyIndex: initialAccuracyIndex,
        initialPeriodicInterval: initialPeriodicInterval,
      );

  /// Feeds a new battery sample into the engine and returns an adjustment event if parameters changed.
  BudgetAdjustmentEvent? processSample({
    required double level,
    required bool isCharging,
    required PlatformInt64 timestampMs,
  });

  /// Resets the engine, dropping historical battery samples.
  void reset();

  /// Returns true if location tracking should be heavily throttled due to low battery budget.
  bool shouldThrottleLocation();
}
