// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../algorithms/impact.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ImpactDetectorDart>>
abstract class ImpactDetectorDart implements RustOpaqueInterface {
  /// Cancels a pending candidate.
  bool cancel({required PlatformInt64 id});

  /// Fires confirmed events for candidates whose deadline elapsed.
  List<ImpactEvent> checkConfirmations({required PlatformInt64 nowMs});

  /// Confirms a pending candidate now.
  ImpactEvent? confirm({
    required PlatformInt64 id,
    required PlatformInt64 nowMs,
  });

  /// Folds a barometric pressure change (hPa) into the most recent pending
  /// crash for the cabin-pressure cue (#173); returns `true` on a corroborating
  /// pressure spike.
  bool corroborateBarometric({
    required double pressureDeltaHpa,
    required PlatformInt64 nowMs,
  });

  /// Folds a post-impact speed sample (m/s) into the most recent pending
  /// crash for Δv corroboration (#181); returns `true` on a corroborating
  /// collapse.
  bool corroborateDv({
    required double speedAfterMps,
    required PlatformInt64 nowMs,
  });

  /// Creates a detector. Pass `None` for defaults (both detections off).
  factory ImpactDetectorDart({ImpactConfig? config}) => RustLib.instance.api
      .crateApiDartImpactImpactDetectorDartNew(config: config);

  /// Feeds one accel-window peak + motion context; returns a `potential_*`
  /// candidate when an impact is detected.
  ImpactEvent? onImpactWindow({
    required double peakG,
    required double speedBeforeMps,
    required double gyroPeakDps,
    required bool wasInFreeFall,
    required bool postImpactStill,
    required bool isOnFoot,
    required double latitude,
    required double longitude,
    required PlatformInt64 nowMs,
  });

  /// Resets all pending candidates.
  void reset();
}
