// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RTreeDart>>
abstract class RTreeDart implements RustOpaqueInterface {
  /// Removes all elements from the R-Tree.
  void clear();

  /// Inserts a new spatial entity into the R-Tree.
  void insert({
    required String id,
    required double lat,
    required double lng,
    required double radiusMeters,
  });

  /// Initializes an empty R-Tree.
  factory RTreeDart() => RustLib.instance.api.crateApiDartRtreeRTreeDartNew();

  /// Queries the R-Tree for entities that intersect with a given circular area.
  List<String> queryCircle({
    required double lat,
    required double lng,
    required double radiusMeters,
  });

  /// Searches the R-Tree for any bounding boxes that intersect with the given point.
  List<String> search({required double lat, required double lng});
}
