// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ScheduleParserDart>>
abstract class ScheduleParserDart implements RustOpaqueInterface {
  /// Calculates the next start and stop UNIX timestamps (in ms) for the provided schedules.
  ScheduleAlarmsDart calculateNextAlarms({
    required List<String> schedules,
    required PlatformInt64 timestampMs,
    required int tzOffsetSeconds,
  });

  /// Evaluates whether the given timestamp falls within any of the provided schedules.
  /// Schedules must be formatted as "dayStart-dayEnd HH:mm-HH:mm" strings.
  bool isWithinSchedule({
    required List<String> schedules,
    required PlatformInt64 timestampMs,
    required int tzOffsetSeconds,
  });

  /// Initializes a new ScheduleParser.
  factory ScheduleParserDart() =>
      RustLib.instance.api.crateApiDartScheduleScheduleParserDartNew();
}

/// Contains the calculated next start and stop alarm times based on a schedule.
class ScheduleAlarmsDart {
  final PlatformInt64 nextStartMs;
  final PlatformInt64 nextStopMs;

  const ScheduleAlarmsDart({
    required this.nextStartMs,
    required this.nextStopMs,
  });

  @override
  int get hashCode => nextStartMs.hashCode ^ nextStopMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScheduleAlarmsDart &&
          runtimeType == other.runtimeType &&
          nextStartMs == other.nextStartMs &&
          nextStopMs == other.nextStopMs;
}
