// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SmartMotionCoordinatorDart>>
abstract class SmartMotionCoordinatorDart implements RustOpaqueInterface {
  /// Returns whether the device is currently considered to be moving.
  bool isMoving();

  /// Creates a new instance of SmartMotionCoordinator.
  factory SmartMotionCoordinatorDart() => RustLib.instance.api
      .crateApiDartSmartMotionSmartMotionCoordinatorDartNew();

  /// Processes an accelerometer event and returns true if motion state changed.
  bool onAccelEvent({
    required double x,
    required double y,
    required double z,
    required PlatformInt64 timestampMs,
  });

  /// Processes a speed change event (e.g., from GPS) and returns true if motion state changed.
  bool onSpeedChanged({required double speed});

  /// Sets the current tracking mode for the coordinator.
  void setTrackingMode({required TrackingModeDart mode});
}

/// Represents the different tracking modes available for the SmartMotionCoordinator.
enum TrackingModeDart {
  /// Actively track location using continuous updates.
  active,

  /// Passive tracking using stationary geofences.
  passive,

  /// Manual tracking mode using periodic updates.
  manual,
}
