// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../algorithms/telematics.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TelematicsEngineDart>>
abstract class TelematicsEngineDart implements RustOpaqueInterface {
  /// Current rolling driving score (0–100).
  double currentScore();

  /// Creates an engine. Pass `None` for default thresholds.
  factory TelematicsEngineDart({TelematicsConfig? config}) => RustLib
      .instance
      .api
      .crateApiDartTelematicsTelematicsEngineDartNew(config: config);

  /// Feeds one fix (speed m/s, heading deg, epoch ms) and returns events.
  List<DrivingEvent> processFix({
    required double speed,
    required double heading,
    required double latitude,
    required double longitude,
    required PlatformInt64 timestampMs,
  });

  /// Resets engine state.
  void reset();
}
