// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../algorithms/transport_mode.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransportModeClassifierDart>>
abstract class TransportModeClassifierDart implements RustOpaqueInterface {
  /// Convenience: computes an accel window from raw magnitudes (g) and
  /// classifies it together with `speed_mps`. Returns the committed mode.
  ModeResult classifySamples({
    required List<double> magnitudesG,
    required PlatformInt64 durationMs,
    required double speedMps,
    required PlatformInt64 nowMs,
  });

  /// Creates a classifier. Pass `None` for default tuning.
  factory TransportModeClassifierDart({ClassifierConfig? config}) => RustLib
      .instance
      .api
      .crateApiDartTransportModeTransportModeClassifierDartNew(config: config);

  /// Resets to `Unknown`.
  void reset();
}
