// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TripManagerDart>>
abstract class TripManagerDart implements RustOpaqueInterface {
  /// Returns true if a trip is actively being recorded.
  bool isTripActive();

  /// Initializes a new TripManager.
  factory TripManagerDart() =>
      RustLib.instance.api.crateApiDartTripTripManagerDartNew();

  /// Feeds a new location point to the trip manager.
  void onLocationReceived({
    required double latitude,
    required double longitude,
    required PlatformInt64 timestampMs,
  });

  /// Updates the motion state and returns trip data if a trip has just ended.
  TripDataDart? onMotionStateChanged({
    required bool isMoving,
    double? latitude,
    double? longitude,
    required PlatformInt64 timestampMs,
    required PlatformInt64 nowMs,
  });

  /// Resets the trip manager, discarding any active trip.
  void reset();
}

/// Contains the comprehensive data for a completed trip.
class TripDataDart {
  final double distanceMeters;
  final double durationSeconds;
  final TripLocationDart? startLocation;
  final TripLocationDart? stopLocation;
  final List<TripWaypointDart> waypoints;

  const TripDataDart({
    required this.distanceMeters,
    required this.durationSeconds,
    this.startLocation,
    this.stopLocation,
    required this.waypoints,
  });

  @override
  int get hashCode =>
      distanceMeters.hashCode ^
      durationSeconds.hashCode ^
      startLocation.hashCode ^
      stopLocation.hashCode ^
      waypoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripDataDart &&
          runtimeType == other.runtimeType &&
          distanceMeters == other.distanceMeters &&
          durationSeconds == other.durationSeconds &&
          startLocation == other.startLocation &&
          stopLocation == other.stopLocation &&
          waypoints == other.waypoints;
}

/// Represents a geographical location (start or stop) of a trip.
class TripLocationDart {
  final double latitude;
  final double longitude;

  const TripLocationDart({required this.latitude, required this.longitude});

  @override
  int get hashCode => latitude.hashCode ^ longitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripLocationDart &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude;
}

/// Represents a single waypoint along a tracked trip.
class TripWaypointDart {
  final double latitude;
  final double longitude;
  final PlatformInt64 timestampMs;

  const TripWaypointDart({
    required this.latitude,
    required this.longitude,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      latitude.hashCode ^ longitude.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripWaypointDart &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          timestampMs == other.timestampMs;
}
