// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// No need to import tracelet_coreFFI, it's bundled in the TraceletSDK module.

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_tracelet_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_tracelet_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTraceletCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol AdaptiveSamplingEngineProtocol: AnyObject, Sendable {
    
    func compute(context: AdaptiveContext)  -> AdaptiveSamplingResult
    
}
open class AdaptiveSamplingEngine: AdaptiveSamplingEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_tracelet_core_fn_clone_adaptivesamplingengine(self.handle, $0) }
    }
public convenience init(baseDistanceFilter: Double, elasticityMultiplier: Double) {
    let handle =
        try! rustCall() {
    uniffi_tracelet_core_fn_constructor_adaptivesamplingengine_new(
        FfiConverterDouble.lower(baseDistanceFilter),
        FfiConverterDouble.lower(elasticityMultiplier),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_tracelet_core_fn_free_adaptivesamplingengine(handle, $0) }
    }

    

    
open func compute(context: AdaptiveContext) -> AdaptiveSamplingResult  {
    return try!  FfiConverterTypeAdaptiveSamplingResult_lift(try! rustCall() {
    uniffi_tracelet_core_fn_method_adaptivesamplingengine_compute(
            self.uniffiCloneHandle(),
        FfiConverterTypeAdaptiveContext_lower(context),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAdaptiveSamplingEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AdaptiveSamplingEngine

    public static func lift(_ handle: UInt64) throws -> AdaptiveSamplingEngine {
        return AdaptiveSamplingEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AdaptiveSamplingEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AdaptiveSamplingEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AdaptiveSamplingEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAdaptiveSamplingEngine_lift(_ handle: UInt64) throws -> AdaptiveSamplingEngine {
    return try FfiConverterTypeAdaptiveSamplingEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAdaptiveSamplingEngine_lower(_ value: AdaptiveSamplingEngine) -> UInt64 {
    return FfiConverterTypeAdaptiveSamplingEngine.lower(value)
}






public protocol GeofenceEvaluatorProtocol: AnyObject, Sendable {
    
    func clear() 
    
    func clearIndex() 
    
    func evaluateProximity(latitude: Double, longitude: Double, geofences: [CoreGeofence])  -> [GeofenceTransition]
    
    func indexGeofences(geofences: [CoreGeofence]) 
    
    func removeGeofence(identifier: String) 
    
}
open class GeofenceEvaluator: GeofenceEvaluatorProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_tracelet_core_fn_clone_geofenceevaluator(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_tracelet_core_fn_constructor_geofenceevaluator_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_tracelet_core_fn_free_geofenceevaluator(handle, $0) }
    }

    

    
open func clear()  {try! rustCall() {
    uniffi_tracelet_core_fn_method_geofenceevaluator_clear(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func clearIndex()  {try! rustCall() {
    uniffi_tracelet_core_fn_method_geofenceevaluator_clear_index(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func evaluateProximity(latitude: Double, longitude: Double, geofences: [CoreGeofence]) -> [GeofenceTransition]  {
    return try!  FfiConverterSequenceTypeGeofenceTransition.lift(try! rustCall() {
    uniffi_tracelet_core_fn_method_geofenceevaluator_evaluate_proximity(
            self.uniffiCloneHandle(),
        FfiConverterDouble.lower(latitude),
        FfiConverterDouble.lower(longitude),
        FfiConverterSequenceTypeCoreGeofence.lower(geofences),$0
    )
})
}
    
open func indexGeofences(geofences: [CoreGeofence])  {try! rustCall() {
    uniffi_tracelet_core_fn_method_geofenceevaluator_index_geofences(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeCoreGeofence.lower(geofences),$0
    )
}
}
    
open func removeGeofence(identifier: String)  {try! rustCall() {
    uniffi_tracelet_core_fn_method_geofenceevaluator_remove_geofence(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(identifier),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGeofenceEvaluator: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = GeofenceEvaluator

    public static func lift(_ handle: UInt64) throws -> GeofenceEvaluator {
        return GeofenceEvaluator(unsafeFromHandle: handle)
    }

    public static func lower(_ value: GeofenceEvaluator) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GeofenceEvaluator {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: GeofenceEvaluator, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeofenceEvaluator_lift(_ handle: UInt64) throws -> GeofenceEvaluator {
    return try FfiConverterTypeGeofenceEvaluator.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeofenceEvaluator_lower(_ value: GeofenceEvaluator) -> UInt64 {
    return FfiConverterTypeGeofenceEvaluator.lower(value)
}






public protocol KalmanLocationFilterProtocol: AnyObject, Sendable {
    
    func estimatedSpeed()  -> Double
    
    func isInitialized()  -> Bool
    
    func process(latitude: Double, longitude: Double, accuracy: Double, timestampMs: Int64)  -> LatLng
    
    func reset() 
    
}
open class KalmanLocationFilter: KalmanLocationFilterProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_tracelet_core_fn_clone_kalmanlocationfilter(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_tracelet_core_fn_constructor_kalmanlocationfilter_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_tracelet_core_fn_free_kalmanlocationfilter(handle, $0) }
    }

    

    
open func estimatedSpeed() -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_tracelet_core_fn_method_kalmanlocationfilter_estimated_speed(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func isInitialized() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tracelet_core_fn_method_kalmanlocationfilter_is_initialized(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func process(latitude: Double, longitude: Double, accuracy: Double, timestampMs: Int64) -> LatLng  {
    return try!  FfiConverterTypeLatLng_lift(try! rustCall() {
    uniffi_tracelet_core_fn_method_kalmanlocationfilter_process(
            self.uniffiCloneHandle(),
        FfiConverterDouble.lower(latitude),
        FfiConverterDouble.lower(longitude),
        FfiConverterDouble.lower(accuracy),
        FfiConverterInt64.lower(timestampMs),$0
    )
})
}
    
open func reset()  {try! rustCall() {
    uniffi_tracelet_core_fn_method_kalmanlocationfilter_reset(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKalmanLocationFilter: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = KalmanLocationFilter

    public static func lift(_ handle: UInt64) throws -> KalmanLocationFilter {
        return KalmanLocationFilter(unsafeFromHandle: handle)
    }

    public static func lower(_ value: KalmanLocationFilter) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KalmanLocationFilter {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: KalmanLocationFilter, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKalmanLocationFilter_lift(_ handle: UInt64) throws -> KalmanLocationFilter {
    return try FfiConverterTypeKalmanLocationFilter.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKalmanLocationFilter_lower(_ value: KalmanLocationFilter) -> UInt64 {
    return FfiConverterTypeKalmanLocationFilter.lower(value)
}






public protocol LocationProcessorProtocol: AnyObject, Sendable {
    
    func hasLastLocation()  -> Bool
    
    func lastEffectiveSpeed()  -> Double
    
    func process(latitude: Double, longitude: Double, accuracy: Double, speed: Double, timestampMs: Int64, isMock: Bool, adaptiveContext: AdaptiveContext?)  -> LocationProcessorResult
    
    func reset() 
    
}
open class LocationProcessor: LocationProcessorProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_tracelet_core_fn_clone_locationprocessor(self.handle, $0) }
    }
public convenience init(distanceFilter: Double, disableElasticity: Bool, elasticityMultiplier: Double, enableAdaptiveMode: Bool, trackingAccuracyThreshold: Int32, filterPolicy: Int32, maxImpliedSpeed: Int32, odometerAccuracyThreshold: Int32, rejectMockLocations: Bool, mockDetectionLevel: Int32, enableSparseUpdates: Bool, sparseDistanceThreshold: Double, sparseMaxIdleSeconds: Int32) {
    let handle =
        try! rustCall() {
    uniffi_tracelet_core_fn_constructor_locationprocessor_new(
        FfiConverterDouble.lower(distanceFilter),
        FfiConverterBool.lower(disableElasticity),
        FfiConverterDouble.lower(elasticityMultiplier),
        FfiConverterBool.lower(enableAdaptiveMode),
        FfiConverterInt32.lower(trackingAccuracyThreshold),
        FfiConverterInt32.lower(filterPolicy),
        FfiConverterInt32.lower(maxImpliedSpeed),
        FfiConverterInt32.lower(odometerAccuracyThreshold),
        FfiConverterBool.lower(rejectMockLocations),
        FfiConverterInt32.lower(mockDetectionLevel),
        FfiConverterBool.lower(enableSparseUpdates),
        FfiConverterDouble.lower(sparseDistanceThreshold),
        FfiConverterInt32.lower(sparseMaxIdleSeconds),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_tracelet_core_fn_free_locationprocessor(handle, $0) }
    }

    

    
open func hasLastLocation() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tracelet_core_fn_method_locationprocessor_has_last_location(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func lastEffectiveSpeed() -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_tracelet_core_fn_method_locationprocessor_last_effective_speed(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func process(latitude: Double, longitude: Double, accuracy: Double, speed: Double, timestampMs: Int64, isMock: Bool, adaptiveContext: AdaptiveContext?) -> LocationProcessorResult  {
    return try!  FfiConverterTypeLocationProcessorResult_lift(try! rustCall() {
    uniffi_tracelet_core_fn_method_locationprocessor_process(
            self.uniffiCloneHandle(),
        FfiConverterDouble.lower(latitude),
        FfiConverterDouble.lower(longitude),
        FfiConverterDouble.lower(accuracy),
        FfiConverterDouble.lower(speed),
        FfiConverterInt64.lower(timestampMs),
        FfiConverterBool.lower(isMock),
        FfiConverterOptionTypeAdaptiveContext.lower(adaptiveContext),$0
    )
})
}
    
open func reset()  {try! rustCall() {
    uniffi_tracelet_core_fn_method_locationprocessor_reset(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLocationProcessor: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = LocationProcessor

    public static func lift(_ handle: UInt64) throws -> LocationProcessor {
        return LocationProcessor(unsafeFromHandle: handle)
    }

    public static func lower(_ value: LocationProcessor) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LocationProcessor {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: LocationProcessor, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocationProcessor_lift(_ handle: UInt64) throws -> LocationProcessor {
    return try FfiConverterTypeLocationProcessor.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocationProcessor_lower(_ value: LocationProcessor) -> UInt64 {
    return FfiConverterTypeLocationProcessor.lower(value)
}




public struct AdaptiveContext: Equatable, Hashable {
    public var batteryLevel: Double
    public var isCharging: Bool
    public var activityType: ActivityType
    public var activityConfidence: ActivityConfidence
    public var speed: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(batteryLevel: Double, isCharging: Bool, activityType: ActivityType, activityConfidence: ActivityConfidence, speed: Double) {
        self.batteryLevel = batteryLevel
        self.isCharging = isCharging
        self.activityType = activityType
        self.activityConfidence = activityConfidence
        self.speed = speed
    }

    

    
}

#if compiler(>=6)
extension AdaptiveContext: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAdaptiveContext: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AdaptiveContext {
        return
            try AdaptiveContext(
                batteryLevel: FfiConverterDouble.read(from: &buf), 
                isCharging: FfiConverterBool.read(from: &buf), 
                activityType: FfiConverterTypeActivityType.read(from: &buf), 
                activityConfidence: FfiConverterTypeActivityConfidence.read(from: &buf), 
                speed: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: AdaptiveContext, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.batteryLevel, into: &buf)
        FfiConverterBool.write(value.isCharging, into: &buf)
        FfiConverterTypeActivityType.write(value.activityType, into: &buf)
        FfiConverterTypeActivityConfidence.write(value.activityConfidence, into: &buf)
        FfiConverterDouble.write(value.speed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAdaptiveContext_lift(_ buf: RustBuffer) throws -> AdaptiveContext {
    return try FfiConverterTypeAdaptiveContext.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAdaptiveContext_lower(_ value: AdaptiveContext) -> RustBuffer {
    return FfiConverterTypeAdaptiveContext.lower(value)
}


public struct AdaptiveSamplingResult: Equatable, Hashable {
    public var effectiveDistanceFilter: Double
    public var baseDistanceFilter: Double
    public var activityFactor: Double
    public var batteryFactor: Double
    public var speedFactor: Double
    public var source: AdaptiveSource

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(effectiveDistanceFilter: Double, baseDistanceFilter: Double, activityFactor: Double, batteryFactor: Double, speedFactor: Double, source: AdaptiveSource) {
        self.effectiveDistanceFilter = effectiveDistanceFilter
        self.baseDistanceFilter = baseDistanceFilter
        self.activityFactor = activityFactor
        self.batteryFactor = batteryFactor
        self.speedFactor = speedFactor
        self.source = source
    }

    

    
}

#if compiler(>=6)
extension AdaptiveSamplingResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAdaptiveSamplingResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AdaptiveSamplingResult {
        return
            try AdaptiveSamplingResult(
                effectiveDistanceFilter: FfiConverterDouble.read(from: &buf), 
                baseDistanceFilter: FfiConverterDouble.read(from: &buf), 
                activityFactor: FfiConverterDouble.read(from: &buf), 
                batteryFactor: FfiConverterDouble.read(from: &buf), 
                speedFactor: FfiConverterDouble.read(from: &buf), 
                source: FfiConverterTypeAdaptiveSource.read(from: &buf)
        )
    }

    public static func write(_ value: AdaptiveSamplingResult, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.effectiveDistanceFilter, into: &buf)
        FfiConverterDouble.write(value.baseDistanceFilter, into: &buf)
        FfiConverterDouble.write(value.activityFactor, into: &buf)
        FfiConverterDouble.write(value.batteryFactor, into: &buf)
        FfiConverterDouble.write(value.speedFactor, into: &buf)
        FfiConverterTypeAdaptiveSource.write(value.source, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAdaptiveSamplingResult_lift(_ buf: RustBuffer) throws -> AdaptiveSamplingResult {
    return try FfiConverterTypeAdaptiveSamplingResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAdaptiveSamplingResult_lower(_ value: AdaptiveSamplingResult) -> RustBuffer {
    return FfiConverterTypeAdaptiveSamplingResult.lower(value)
}


public struct Coordinate: Equatable, Hashable {
    public var lat: Double
    public var lng: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(lat: Double, lng: Double) {
        self.lat = lat
        self.lng = lng
    }

    

    
}

#if compiler(>=6)
extension Coordinate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoordinate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Coordinate {
        return
            try Coordinate(
                lat: FfiConverterDouble.read(from: &buf), 
                lng: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Coordinate, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.lat, into: &buf)
        FfiConverterDouble.write(value.lng, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoordinate_lift(_ buf: RustBuffer) throws -> Coordinate {
    return try FfiConverterTypeCoordinate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoordinate_lower(_ value: Coordinate) -> RustBuffer {
    return FfiConverterTypeCoordinate.lower(value)
}


public struct CoreGeofence: Equatable, Hashable {
    public var identifier: String
    public var latitude: Double
    public var longitude: Double
    public var radius: Double
    public var vertices: [Coordinate]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identifier: String, latitude: Double, longitude: Double, radius: Double, vertices: [Coordinate]) {
        self.identifier = identifier
        self.latitude = latitude
        self.longitude = longitude
        self.radius = radius
        self.vertices = vertices
    }

    

    
}

#if compiler(>=6)
extension CoreGeofence: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreGeofence: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreGeofence {
        return
            try CoreGeofence(
                identifier: FfiConverterString.read(from: &buf), 
                latitude: FfiConverterDouble.read(from: &buf), 
                longitude: FfiConverterDouble.read(from: &buf), 
                radius: FfiConverterDouble.read(from: &buf), 
                vertices: FfiConverterSequenceTypeCoordinate.read(from: &buf)
        )
    }

    public static func write(_ value: CoreGeofence, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identifier, into: &buf)
        FfiConverterDouble.write(value.latitude, into: &buf)
        FfiConverterDouble.write(value.longitude, into: &buf)
        FfiConverterDouble.write(value.radius, into: &buf)
        FfiConverterSequenceTypeCoordinate.write(value.vertices, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreGeofence_lift(_ buf: RustBuffer) throws -> CoreGeofence {
    return try FfiConverterTypeCoreGeofence.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreGeofence_lower(_ value: CoreGeofence) -> RustBuffer {
    return FfiConverterTypeCoreGeofence.lower(value)
}


public struct GeofenceTransition: Equatable, Hashable {
    public var identifier: String
    public var action: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identifier: String, action: String) {
        self.identifier = identifier
        self.action = action
    }

    

    
}

#if compiler(>=6)
extension GeofenceTransition: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGeofenceTransition: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GeofenceTransition {
        return
            try GeofenceTransition(
                identifier: FfiConverterString.read(from: &buf), 
                action: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: GeofenceTransition, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identifier, into: &buf)
        FfiConverterString.write(value.action, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeofenceTransition_lift(_ buf: RustBuffer) throws -> GeofenceTransition {
    return try FfiConverterTypeGeofenceTransition.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeofenceTransition_lower(_ value: GeofenceTransition) -> RustBuffer {
    return FfiConverterTypeGeofenceTransition.lower(value)
}


public struct LatLng: Equatable, Hashable {
    public var latitude: Double
    public var longitude: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(latitude: Double, longitude: Double) {
        self.latitude = latitude
        self.longitude = longitude
    }

    

    
}

#if compiler(>=6)
extension LatLng: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLatLng: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LatLng {
        return
            try LatLng(
                latitude: FfiConverterDouble.read(from: &buf), 
                longitude: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: LatLng, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.latitude, into: &buf)
        FfiConverterDouble.write(value.longitude, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLatLng_lift(_ buf: RustBuffer) throws -> LatLng {
    return try FfiConverterTypeLatLng.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLatLng_lower(_ value: LatLng) -> RustBuffer {
    return FfiConverterTypeLatLng.lower(value)
}


public struct LocationProcessorResult: Equatable, Hashable {
    public var accepted: Bool
    public var effectiveSpeed: Double
    public var odometerDelta: Double
    public var distance: Double
    public var reason: String?
    public var errorMessage: String?
    public var isError: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(accepted: Bool, effectiveSpeed: Double, odometerDelta: Double, distance: Double, reason: String?, errorMessage: String?, isError: Bool) {
        self.accepted = accepted
        self.effectiveSpeed = effectiveSpeed
        self.odometerDelta = odometerDelta
        self.distance = distance
        self.reason = reason
        self.errorMessage = errorMessage
        self.isError = isError
    }

    

    
}

#if compiler(>=6)
extension LocationProcessorResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLocationProcessorResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LocationProcessorResult {
        return
            try LocationProcessorResult(
                accepted: FfiConverterBool.read(from: &buf), 
                effectiveSpeed: FfiConverterDouble.read(from: &buf), 
                odometerDelta: FfiConverterDouble.read(from: &buf), 
                distance: FfiConverterDouble.read(from: &buf), 
                reason: FfiConverterOptionString.read(from: &buf), 
                errorMessage: FfiConverterOptionString.read(from: &buf), 
                isError: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: LocationProcessorResult, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.accepted, into: &buf)
        FfiConverterDouble.write(value.effectiveSpeed, into: &buf)
        FfiConverterDouble.write(value.odometerDelta, into: &buf)
        FfiConverterDouble.write(value.distance, into: &buf)
        FfiConverterOptionString.write(value.reason, into: &buf)
        FfiConverterOptionString.write(value.errorMessage, into: &buf)
        FfiConverterBool.write(value.isError, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocationProcessorResult_lift(_ buf: RustBuffer) throws -> LocationProcessorResult {
    return try FfiConverterTypeLocationProcessorResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocationProcessorResult_lower(_ value: LocationProcessorResult) -> RustBuffer {
    return FfiConverterTypeLocationProcessorResult.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ActivityConfidence: Equatable, Hashable {
    
    case low
    case medium
    case high





}

#if compiler(>=6)
extension ActivityConfidence: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeActivityConfidence: FfiConverterRustBuffer {
    typealias SwiftType = ActivityConfidence

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ActivityConfidence {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .low
        
        case 2: return .medium
        
        case 3: return .high
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ActivityConfidence, into buf: inout [UInt8]) {
        switch value {
        
        
        case .low:
            writeInt(&buf, Int32(1))
        
        
        case .medium:
            writeInt(&buf, Int32(2))
        
        
        case .high:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeActivityConfidence_lift(_ buf: RustBuffer) throws -> ActivityConfidence {
    return try FfiConverterTypeActivityConfidence.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeActivityConfidence_lower(_ value: ActivityConfidence) -> RustBuffer {
    return FfiConverterTypeActivityConfidence.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ActivityType: Equatable, Hashable {
    
    case still
    case walking
    case running
    case onFoot
    case inVehicle
    case onBicycle
    case unknown





}

#if compiler(>=6)
extension ActivityType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeActivityType: FfiConverterRustBuffer {
    typealias SwiftType = ActivityType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ActivityType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .still
        
        case 2: return .walking
        
        case 3: return .running
        
        case 4: return .onFoot
        
        case 5: return .inVehicle
        
        case 6: return .onBicycle
        
        case 7: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ActivityType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .still:
            writeInt(&buf, Int32(1))
        
        
        case .walking:
            writeInt(&buf, Int32(2))
        
        
        case .running:
            writeInt(&buf, Int32(3))
        
        
        case .onFoot:
            writeInt(&buf, Int32(4))
        
        
        case .inVehicle:
            writeInt(&buf, Int32(5))
        
        
        case .onBicycle:
            writeInt(&buf, Int32(6))
        
        
        case .unknown:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeActivityType_lift(_ buf: RustBuffer) throws -> ActivityType {
    return try FfiConverterTypeActivityType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeActivityType_lower(_ value: ActivityType) -> RustBuffer {
    return FfiConverterTypeActivityType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AdaptiveSource: Equatable, Hashable {
    
    case activity
    case speed
    case `static`





}

#if compiler(>=6)
extension AdaptiveSource: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAdaptiveSource: FfiConverterRustBuffer {
    typealias SwiftType = AdaptiveSource

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AdaptiveSource {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .activity
        
        case 2: return .speed
        
        case 3: return .`static`
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AdaptiveSource, into buf: inout [UInt8]) {
        switch value {
        
        
        case .activity:
            writeInt(&buf, Int32(1))
        
        
        case .speed:
            writeInt(&buf, Int32(2))
        
        
        case .`static`:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAdaptiveSource_lift(_ buf: RustBuffer) throws -> AdaptiveSource {
    return try FfiConverterTypeAdaptiveSource.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAdaptiveSource_lower(_ value: AdaptiveSource) -> RustBuffer {
    return FfiConverterTypeAdaptiveSource.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAdaptiveContext: FfiConverterRustBuffer {
    typealias SwiftType = AdaptiveContext?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAdaptiveContext.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAdaptiveContext.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCoordinate: FfiConverterRustBuffer {
    typealias SwiftType = [Coordinate]

    public static func write(_ value: [Coordinate], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCoordinate.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Coordinate] {
        let len: Int32 = try readInt(&buf)
        var seq = [Coordinate]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCoordinate.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCoreGeofence: FfiConverterRustBuffer {
    typealias SwiftType = [CoreGeofence]

    public static func write(_ value: [CoreGeofence], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCoreGeofence.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CoreGeofence] {
        let len: Int32 = try readInt(&buf)
        var seq = [CoreGeofence]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCoreGeofence.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGeofenceTransition: FfiConverterRustBuffer {
    typealias SwiftType = [GeofenceTransition]

    public static func write(_ value: [GeofenceTransition], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGeofenceTransition.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [GeofenceTransition] {
        let len: Int32 = try readInt(&buf)
        var seq = [GeofenceTransition]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGeofenceTransition.read(from: &buf))
        }
        return seq
    }
}
public func haversine(lat1: Double, lon1: Double, lat2: Double, lon2: Double) -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_tracelet_core_fn_func_haversine(
        FfiConverterDouble.lower(lat1),
        FfiConverterDouble.lower(lon1),
        FfiConverterDouble.lower(lat2),
        FfiConverterDouble.lower(lon2),$0
    )
})
}
public func isPointInPolygon(lat: Double, lng: Double, vertices: [Coordinate]) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tracelet_core_fn_func_is_point_in_polygon(
        FfiConverterDouble.lower(lat),
        FfiConverterDouble.lower(lng),
        FfiConverterSequenceTypeCoordinate.lower(vertices),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_tracelet_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_tracelet_core_checksum_func_haversine() != 50519) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_func_is_point_in_polygon() != 57508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_kalmanlocationfilter_estimated_speed() != 60857) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_kalmanlocationfilter_is_initialized() != 40389) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_kalmanlocationfilter_process() != 5966) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_kalmanlocationfilter_reset() != 3495) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_adaptivesamplingengine_compute() != 3823) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_locationprocessor_has_last_location() != 24404) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_locationprocessor_last_effective_speed() != 13698) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_locationprocessor_process() != 9433) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_locationprocessor_reset() != 105) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_geofenceevaluator_clear() != 7402) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_geofenceevaluator_clear_index() != 13907) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_geofenceevaluator_evaluate_proximity() != 35353) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_geofenceevaluator_index_geofences() != 8803) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_method_geofenceevaluator_remove_geofence() != 46486) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_constructor_kalmanlocationfilter_new() != 58796) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_constructor_adaptivesamplingengine_new() != 3978) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_constructor_locationprocessor_new() != 1269) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tracelet_core_checksum_constructor_geofenceevaluator_new() != 56699) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTraceletCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all