import 'dart:convert';

import 'package:tracelet/tracelet.dart';

/// Builds a single, copy-and-paste-friendly **bug report** that bundles
/// everything a maintainer needs to triage a Tracelet issue:
///
/// 1. The diagnostic [HealthCheck] (permissions, battery/OEM, sensors, device).
/// 2. The **active configuration** (`Tracelet.activeConfig`) — with secrets
///    automatically redacted.
/// 3. The most recent **device logs** (`Tracelet.getLogs`).
/// 4. The most recent **telematics events** (`Tracelet.getTelematicsEvents`).
///
/// The output is GitHub-flavoured Markdown, ready to drop straight into an
/// issue. Every section is gathered defensively — if one source fails (e.g.
/// the plugin isn't initialized), that section reports the error instead of
/// failing the whole report.
///
/// ```dart
/// final report = await TraceletBugReport.build();
/// await Clipboard.setData(ClipboardData(text: report));
/// // or: await Share.share(report);
/// ```
class TraceletBugReport {
  TraceletBugReport._();

  /// Header keys (case-insensitive, substring match) whose values are masked
  /// before the configuration is included in the report. Prevents API keys,
  /// auth tokens, URLs and pinning material from leaking into a pasted issue.
  static const List<String> _sensitiveKeyHints = [
    'url',
    'header',
    'param',
    'extra',
    'token',
    'secret',
    'key',
    'password',
    'auth',
    'fingerprint',
    'certificate',
    'credential',
  ];

  /// Builds the full Markdown bug report.
  ///
  /// - [logLimit] — how many recent log entries to include (default 500).
  /// - [telematicsLimit] — how many recent telematics events to include
  ///   (default 100).
  /// - [appName] / [appVersion] — optional host-app identifiers shown in the
  ///   header (your `package_info_plus` values, for example).
  /// - [includeConfig] — set `false` to omit the configuration section.
  static Future<String> build({
    int logLimit = 500,
    int telematicsLimit = 100,
    String? appName,
    String? appVersion,
    bool includeConfig = true,
  }) async {
    final buffer = StringBuffer();
    final now = DateTime.now().toUtc().toIso8601String();

    buffer.writeln('# Tracelet Bug Report');
    buffer.writeln();
    buffer.writeln('_Generated by Tracelet Doctor at $now (UTC)._');
    if (appName != null || appVersion != null) {
      buffer.writeln();
      buffer.writeln('- **App:** ${appName ?? '—'} ${appVersion ?? ''}'.trim());
    }
    buffer.writeln();
    buffer.writeln(
      '> ⚠️ This report may include device and configuration '
      'details. Secrets (URLs, headers, keys) are redacted, but please '
      'review before sharing publicly.',
    );
    buffer.writeln();

    await _writeHealth(buffer);
    if (includeConfig) _writeConfig(buffer);
    await _writeTelematics(buffer, telematicsLimit);
    await _writeLogs(buffer, logLimit);

    return buffer.toString();
  }

  // ---------------------------------------------------------------------------
  // Sections
  // ---------------------------------------------------------------------------

  static Future<void> _writeHealth(StringBuffer buffer) async {
    buffer.writeln('## Health check');
    buffer.writeln();
    try {
      final health = await Tracelet.getHealth();
      buffer.writeln('| Field | Value |');
      buffer.writeln('|---|---|');
      buffer.writeln('| Platform | ${health.platform} |');
      buffer.writeln('| OS version | ${health.osVersion} |');
      buffer.writeln('| Manufacturer | ${health.manufacturer} |');
      buffer.writeln('| Model | ${health.model} |');
      buffer.writeln(
        '| Aggressive OEM | ${health.isAggressiveOem} '
        '(rating ${health.aggressionRating}/5) |',
      );
      buffer.writeln('| Tracking enabled | ${health.trackingEnabled} |');
      buffer.writeln('| Tracking mode | ${health.trackingMode.name} |');
      buffer.writeln('| Is moving | ${health.isMoving} |');
      buffer.writeln(
        '| Odometer (m) | ${health.odometer.toStringAsFixed(1)} |',
      );
      buffer.writeln(
        '| Location permission | ${health.locationPermission.name} |',
      );
      buffer.writeln('| Motion permission | ${health.motionPermission} |');
      buffer.writeln('| Accuracy | ${health.accuracyAuthorization.name} |');
      buffer.writeln(
        '| Location services | ${health.locationServicesEnabled} |',
      );
      buffer.writeln('| Power save mode | ${health.isPowerSaveMode} |');
      buffer.writeln(
        '| Ignoring battery opt | ${health.isIgnoringBatteryOptimizations} |',
      );
      buffer.writeln('| Accelerometer | ${health.hasAccelerometer} |');
      buffer.writeln('| Gyroscope | ${health.hasGyroscope} |');
      buffer.writeln('| Magnetometer | ${health.hasMagnetometer} |');
      buffer.writeln('| Significant motion | ${health.hasSignificantMotion} |');
      buffer.writeln('| Mock locations | ${health.mockLocationsDetected} |');
      buffer.writeln('| Pending locations | ${health.locationCount} |');
      buffer.writeln();

      if (health.warnings.isEmpty) {
        buffer.writeln('**Warnings:** none — all systems healthy. ✅');
      } else {
        buffer.writeln('**Warnings (${health.warnings.length}):**');
        buffer.writeln();
        for (final w in health.warnings) {
          buffer.writeln('- ⚠️ ${w.description}');
        }
      }
    } catch (e) {
      buffer.writeln('_Could not read health: ${e}_');
    }
    buffer.writeln();
  }

  static void _writeConfig(StringBuffer buffer) {
    buffer.writeln('## Active configuration');
    buffer.writeln();
    try {
      final raw = Tracelet.activeConfig.toMap();
      final redacted = redactConfig(raw);
      final json = const JsonEncoder.withIndent('  ').convert(redacted);
      buffer.writeln('```json');
      buffer.writeln(json);
      buffer.writeln('```');
    } catch (e) {
      buffer.writeln('_Could not read configuration: ${e}_');
    }
    buffer.writeln();
  }

  static Future<void> _writeTelematics(StringBuffer buffer, int limit) async {
    buffer.writeln('## Telematics events (most recent)');
    buffer.writeln();
    try {
      final events = await Tracelet.getTelematicsEvents(limit);
      if (events.isEmpty) {
        buffer.writeln('_No stored telematics events._');
      } else {
        buffer.writeln('| Type | Severity | Lat | Lng | Time | Synced |');
        buffer.writeln('|---|---|---|---|---|---|');
        for (final e in events) {
          buffer.writeln(
            '| ${e.eventType} | ${e.severity.toStringAsFixed(2)} '
            '| ${e.latitude.toStringAsFixed(5)} '
            '| ${e.longitude.toStringAsFixed(5)} '
            '| ${e.timestamp} | ${e.synced} |',
          );
        }
      }
    } catch (e) {
      buffer.writeln('_Could not read telematics events: ${e}_');
    }
    buffer.writeln();
  }

  static Future<void> _writeLogs(StringBuffer buffer, int limit) async {
    buffer.writeln('## Logs (last $limit)');
    buffer.writeln();
    try {
      final logs = await Tracelet.getLogs(limit);
      if (logs.isEmpty) {
        buffer.writeln('_No logs recorded._');
      } else {
        buffer.writeln('```');
        for (final log in logs) {
          buffer.writeln(
            '${log.timestamp} [${log.level.toUpperCase()}] ${log.message}',
          );
        }
        buffer.writeln('```');
      }
    } catch (e) {
      buffer.writeln('_Could not read logs: ${e}_');
    }
    buffer.writeln();
  }

  // ---------------------------------------------------------------------------
  // Redaction
  // ---------------------------------------------------------------------------

  /// Returns a deep copy of [config] with the values of any secret-looking
  /// keys (URLs, headers, params, keys, tokens, pinning material) replaced by
  /// `«redacted»`. Exposed so apps can safely log or display their own config.
  static Map<String, Object?> redactConfig(Map<String, Object?> config) =>
      (_redact(config)! as Map).cast<String, Object?>();

  /// Recursively masks the values of any key whose name hints at a secret.
  static Object? _redact(Object? value) {
    if (value is Map) {
      final out = <String, Object?>{};
      value.forEach((k, v) {
        final key = k.toString();
        if (_isSensitive(key) && v != null) {
          out[key] = '«redacted»';
        } else {
          out[key] = _redact(v);
        }
      });
      return out;
    }
    if (value is List) {
      return value.map(_redact).toList();
    }
    return value;
  }

  static bool _isSensitive(String key) {
    final lower = key.toLowerCase();
    return _sensitiveKeyHints.any(lower.contains);
  }
}
