import Foundation

@_silgen_name("frb_create_shutdown_callback") func dummy_TraceletCore_frb_create_shutdown_callback()
@_silgen_name("frb_dart_fn_deliver_output") func dummy_TraceletCore_frb_dart_fn_deliver_output()
@_silgen_name("frb_dart_opaque_dart2rust_encode") func dummy_TraceletCore_frb_dart_opaque_dart2rust_encode()
@_silgen_name("frb_dart_opaque_drop_thread_box_persistent_handle") func dummy_TraceletCore_frb_dart_opaque_drop_thread_box_persistent_handle()
@_silgen_name("frb_dart_opaque_rust2dart_decode") func dummy_TraceletCore_frb_dart_opaque_rust2dart_decode()
@_silgen_name("frb_free_wire_sync_rust2dart_dco") func dummy_TraceletCore_frb_free_wire_sync_rust2dart_dco()
@_silgen_name("frb_free_wire_sync_rust2dart_sse") func dummy_TraceletCore_frb_free_wire_sync_rust2dart_sse()
@_silgen_name("frb_get_rust_content_hash") func dummy_TraceletCore_frb_get_rust_content_hash()
@_silgen_name("frb_init_frb_dart_api_dl") func dummy_TraceletCore_frb_init_frb_dart_api_dl()
@_silgen_name("frb_pde_ffi_dispatcher_primary") func dummy_TraceletCore_frb_pde_ffi_dispatcher_primary()
@_silgen_name("frb_pde_ffi_dispatcher_sync") func dummy_TraceletCore_frb_pde_ffi_dispatcher_sync()
@_silgen_name("frb_rust_vec_u8_free") func dummy_TraceletCore_frb_rust_vec_u8_free()
@_silgen_name("frb_rust_vec_u8_new") func dummy_TraceletCore_frb_rust_vec_u8_new()
@_silgen_name("frb_rust_vec_u8_resize") func dummy_TraceletCore_frb_rust_vec_u8_resize()
@_silgen_name("frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart") func dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart()
@_silgen_name("frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart") func dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart()
@_silgen_name("frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart") func dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart()
@_silgen_name("frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart") func dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart()
@_silgen_name("frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart") func dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart()
@_silgen_name("frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart") func dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart()
@_silgen_name("frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart") func dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart()
@_silgen_name("frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart") func dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart()
@_silgen_name("frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart") func dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart()
@_silgen_name("frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart") func dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart()
@_silgen_name("store_dart_post_cobject") func dummy_TraceletCore_store_dart_post_cobject()

public var _TraceletCore_dummy_sink: [Any] = []

public struct TraceletCoreDummy {
    @inline(never)
    public static func enforceBundling() {
        let dummyArray: [Any] = [
            dummy_TraceletCore_frb_create_shutdown_callback as Any,
            dummy_TraceletCore_frb_dart_fn_deliver_output as Any,
            dummy_TraceletCore_frb_dart_opaque_dart2rust_encode as Any,
            dummy_TraceletCore_frb_dart_opaque_drop_thread_box_persistent_handle as Any,
            dummy_TraceletCore_frb_dart_opaque_rust2dart_decode as Any,
            dummy_TraceletCore_frb_free_wire_sync_rust2dart_dco as Any,
            dummy_TraceletCore_frb_free_wire_sync_rust2dart_sse as Any,
            dummy_TraceletCore_frb_get_rust_content_hash as Any,
            dummy_TraceletCore_frb_init_frb_dart_api_dl as Any,
            dummy_TraceletCore_frb_pde_ffi_dispatcher_primary as Any,
            dummy_TraceletCore_frb_pde_ffi_dispatcher_sync as Any,
            dummy_TraceletCore_frb_rust_vec_u8_free as Any,
            dummy_TraceletCore_frb_rust_vec_u8_new as Any,
            dummy_TraceletCore_frb_rust_vec_u8_resize as Any,
            dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart as Any,
            dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart as Any,
            dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart as Any,
            dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart as Any,
            dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart as Any,
            dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart as Any,
            dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart as Any,
            dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart as Any,
            dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart as Any,
            dummy_TraceletCore_frbgen_tracelet_platform_interface_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart as Any,
            dummy_TraceletCore_store_dart_post_cobject as Any,
        ]
        _TraceletCore_dummy_sink = dummyArray
        if ProcessInfo.processInfo.environment["DEBUG_DUMMY_FRB"] != nil {
            print(_TraceletCore_dummy_sink)
        }
    }
}
