// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'algorithms/impact.dart';
import 'algorithms/telematics.dart';
import 'algorithms/transport_mode.dart';
import 'api_dart/battery_budget.dart';
import 'api_dart/impact.dart';
import 'api_dart/rtree.dart';
import 'api_dart/schedule.dart';
import 'api_dart/smart_motion.dart';
import 'api_dart/telematics.dart';
import 'api_dart/transport_mode.dart';
import 'api_dart/trip.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'state/battery_budget.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BatteryBudgetEngineDartPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ImpactDetectorDartPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RTreeDartPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ScheduleParserDartPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SmartMotionCoordinatorDartPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TelematicsEngineDartPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TransportModeClassifierDartPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TripManagerDartPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart;

  @protected
  BatteryBudgetEngineDart
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    dynamic raw,
  );

  @protected
  ImpactDetectorDart
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    dynamic raw,
  );

  @protected
  RTreeDart
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    dynamic raw,
  );

  @protected
  ScheduleParserDart
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    dynamic raw,
  );

  @protected
  SmartMotionCoordinatorDart
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    dynamic raw,
  );

  @protected
  TelematicsEngineDart
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    dynamic raw,
  );

  @protected
  TransportModeClassifierDart
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    dynamic raw,
  );

  @protected
  TripManagerDart
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    dynamic raw,
  );

  @protected
  RTreeDart
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    dynamic raw,
  );

  @protected
  BatteryBudgetEngineDart
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    dynamic raw,
  );

  @protected
  ImpactDetectorDart
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    dynamic raw,
  );

  @protected
  RTreeDart
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    dynamic raw,
  );

  @protected
  ScheduleParserDart
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    dynamic raw,
  );

  @protected
  SmartMotionCoordinatorDart
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    dynamic raw,
  );

  @protected
  TelematicsEngineDart
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    dynamic raw,
  );

  @protected
  TransportModeClassifierDart
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    dynamic raw,
  );

  @protected
  TripManagerDart
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    dynamic raw,
  );

  @protected
  BatteryBudgetEngineDart
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    dynamic raw,
  );

  @protected
  ImpactDetectorDart
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    dynamic raw,
  );

  @protected
  RTreeDart
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    dynamic raw,
  );

  @protected
  ScheduleParserDart
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    dynamic raw,
  );

  @protected
  SmartMotionCoordinatorDart
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    dynamic raw,
  );

  @protected
  TelematicsEngineDart
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    dynamic raw,
  );

  @protected
  TransportModeClassifierDart
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    dynamic raw,
  );

  @protected
  TripManagerDart
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BudgetAdjustmentEvent dco_decode_box_autoadd_budget_adjustment_event(
    dynamic raw,
  );

  @protected
  ClassifierConfig dco_decode_box_autoadd_classifier_config(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  ImpactConfig dco_decode_box_autoadd_impact_config(dynamic raw);

  @protected
  ImpactEvent dco_decode_box_autoadd_impact_event(dynamic raw);

  @protected
  TelematicsConfig dco_decode_box_autoadd_telematics_config(dynamic raw);

  @protected
  TripDataDart dco_decode_box_autoadd_trip_data_dart(dynamic raw);

  @protected
  TripLocationDart dco_decode_box_autoadd_trip_location_dart(dynamic raw);

  @protected
  BudgetAdjustmentEvent dco_decode_budget_adjustment_event(dynamic raw);

  @protected
  ClassifierConfig dco_decode_classifier_config(dynamic raw);

  @protected
  DrivingEvent dco_decode_driving_event(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImpactConfig dco_decode_impact_config(dynamic raw);

  @protected
  ImpactEvent dco_decode_impact_event(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DrivingEvent> dco_decode_list_driving_event(dynamic raw);

  @protected
  List<ImpactEvent> dco_decode_list_impact_event(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TripWaypointDart> dco_decode_list_trip_waypoint_dart(dynamic raw);

  @protected
  ModeResult dco_decode_mode_result(dynamic raw);

  @protected
  BudgetAdjustmentEvent? dco_decode_opt_box_autoadd_budget_adjustment_event(
    dynamic raw,
  );

  @protected
  ClassifierConfig? dco_decode_opt_box_autoadd_classifier_config(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  ImpactConfig? dco_decode_opt_box_autoadd_impact_config(dynamic raw);

  @protected
  ImpactEvent? dco_decode_opt_box_autoadd_impact_event(dynamic raw);

  @protected
  TelematicsConfig? dco_decode_opt_box_autoadd_telematics_config(dynamic raw);

  @protected
  TripDataDart? dco_decode_opt_box_autoadd_trip_data_dart(dynamic raw);

  @protected
  TripLocationDart? dco_decode_opt_box_autoadd_trip_location_dart(dynamic raw);

  @protected
  ScheduleAlarmsDart dco_decode_schedule_alarms_dart(dynamic raw);

  @protected
  TelematicsConfig dco_decode_telematics_config(dynamic raw);

  @protected
  TrackingModeDart dco_decode_tracking_mode_dart(dynamic raw);

  @protected
  TransportMode dco_decode_transport_mode(dynamic raw);

  @protected
  TripDataDart dco_decode_trip_data_dart(dynamic raw);

  @protected
  TripLocationDart dco_decode_trip_location_dart(dynamic raw);

  @protected
  TripWaypointDart dco_decode_trip_waypoint_dart(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  BatteryBudgetEngineDart
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    SseDeserializer deserializer,
  );

  @protected
  ImpactDetectorDart
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    SseDeserializer deserializer,
  );

  @protected
  RTreeDart
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    SseDeserializer deserializer,
  );

  @protected
  ScheduleParserDart
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    SseDeserializer deserializer,
  );

  @protected
  SmartMotionCoordinatorDart
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    SseDeserializer deserializer,
  );

  @protected
  TelematicsEngineDart
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    SseDeserializer deserializer,
  );

  @protected
  TransportModeClassifierDart
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    SseDeserializer deserializer,
  );

  @protected
  TripManagerDart
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    SseDeserializer deserializer,
  );

  @protected
  RTreeDart
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    SseDeserializer deserializer,
  );

  @protected
  BatteryBudgetEngineDart
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    SseDeserializer deserializer,
  );

  @protected
  ImpactDetectorDart
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    SseDeserializer deserializer,
  );

  @protected
  RTreeDart
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    SseDeserializer deserializer,
  );

  @protected
  ScheduleParserDart
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    SseDeserializer deserializer,
  );

  @protected
  SmartMotionCoordinatorDart
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    SseDeserializer deserializer,
  );

  @protected
  TelematicsEngineDart
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    SseDeserializer deserializer,
  );

  @protected
  TransportModeClassifierDart
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    SseDeserializer deserializer,
  );

  @protected
  TripManagerDart
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    SseDeserializer deserializer,
  );

  @protected
  BatteryBudgetEngineDart
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    SseDeserializer deserializer,
  );

  @protected
  ImpactDetectorDart
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    SseDeserializer deserializer,
  );

  @protected
  RTreeDart
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    SseDeserializer deserializer,
  );

  @protected
  ScheduleParserDart
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    SseDeserializer deserializer,
  );

  @protected
  SmartMotionCoordinatorDart
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    SseDeserializer deserializer,
  );

  @protected
  TelematicsEngineDart
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    SseDeserializer deserializer,
  );

  @protected
  TransportModeClassifierDart
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    SseDeserializer deserializer,
  );

  @protected
  TripManagerDart
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BudgetAdjustmentEvent sse_decode_box_autoadd_budget_adjustment_event(
    SseDeserializer deserializer,
  );

  @protected
  ClassifierConfig sse_decode_box_autoadd_classifier_config(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  ImpactConfig sse_decode_box_autoadd_impact_config(
    SseDeserializer deserializer,
  );

  @protected
  ImpactEvent sse_decode_box_autoadd_impact_event(SseDeserializer deserializer);

  @protected
  TelematicsConfig sse_decode_box_autoadd_telematics_config(
    SseDeserializer deserializer,
  );

  @protected
  TripDataDart sse_decode_box_autoadd_trip_data_dart(
    SseDeserializer deserializer,
  );

  @protected
  TripLocationDart sse_decode_box_autoadd_trip_location_dart(
    SseDeserializer deserializer,
  );

  @protected
  BudgetAdjustmentEvent sse_decode_budget_adjustment_event(
    SseDeserializer deserializer,
  );

  @protected
  ClassifierConfig sse_decode_classifier_config(SseDeserializer deserializer);

  @protected
  DrivingEvent sse_decode_driving_event(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImpactConfig sse_decode_impact_config(SseDeserializer deserializer);

  @protected
  ImpactEvent sse_decode_impact_event(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DrivingEvent> sse_decode_list_driving_event(
    SseDeserializer deserializer,
  );

  @protected
  List<ImpactEvent> sse_decode_list_impact_event(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TripWaypointDart> sse_decode_list_trip_waypoint_dart(
    SseDeserializer deserializer,
  );

  @protected
  ModeResult sse_decode_mode_result(SseDeserializer deserializer);

  @protected
  BudgetAdjustmentEvent? sse_decode_opt_box_autoadd_budget_adjustment_event(
    SseDeserializer deserializer,
  );

  @protected
  ClassifierConfig? sse_decode_opt_box_autoadd_classifier_config(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  ImpactConfig? sse_decode_opt_box_autoadd_impact_config(
    SseDeserializer deserializer,
  );

  @protected
  ImpactEvent? sse_decode_opt_box_autoadd_impact_event(
    SseDeserializer deserializer,
  );

  @protected
  TelematicsConfig? sse_decode_opt_box_autoadd_telematics_config(
    SseDeserializer deserializer,
  );

  @protected
  TripDataDart? sse_decode_opt_box_autoadd_trip_data_dart(
    SseDeserializer deserializer,
  );

  @protected
  TripLocationDart? sse_decode_opt_box_autoadd_trip_location_dart(
    SseDeserializer deserializer,
  );

  @protected
  ScheduleAlarmsDart sse_decode_schedule_alarms_dart(
    SseDeserializer deserializer,
  );

  @protected
  TelematicsConfig sse_decode_telematics_config(SseDeserializer deserializer);

  @protected
  TrackingModeDart sse_decode_tracking_mode_dart(SseDeserializer deserializer);

  @protected
  TransportMode sse_decode_transport_mode(SseDeserializer deserializer);

  @protected
  TripDataDart sse_decode_trip_data_dart(SseDeserializer deserializer);

  @protected
  TripLocationDart sse_decode_trip_location_dart(SseDeserializer deserializer);

  @protected
  TripWaypointDart sse_decode_trip_waypoint_dart(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    BatteryBudgetEngineDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    ImpactDetectorDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    RTreeDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    ScheduleParserDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    SmartMotionCoordinatorDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    TelematicsEngineDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    TransportModeClassifierDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    TripManagerDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    RTreeDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    BatteryBudgetEngineDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    ImpactDetectorDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    RTreeDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    ScheduleParserDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    SmartMotionCoordinatorDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    TelematicsEngineDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    TransportModeClassifierDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    TripManagerDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    BatteryBudgetEngineDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    ImpactDetectorDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    RTreeDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    ScheduleParserDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    SmartMotionCoordinatorDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    TelematicsEngineDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    TransportModeClassifierDart self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    TripManagerDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_budget_adjustment_event(
    BudgetAdjustmentEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_classifier_config(
    ClassifierConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_impact_config(
    ImpactConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_impact_event(
    ImpactEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_telematics_config(
    TelematicsConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_trip_data_dart(
    TripDataDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_trip_location_dart(
    TripLocationDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_budget_adjustment_event(
    BudgetAdjustmentEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_classifier_config(
    ClassifierConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_driving_event(DrivingEvent self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_impact_config(ImpactConfig self, SseSerializer serializer);

  @protected
  void sse_encode_impact_event(ImpactEvent self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_driving_event(
    List<DrivingEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_impact_event(
    List<ImpactEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trip_waypoint_dart(
    List<TripWaypointDart> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mode_result(ModeResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_budget_adjustment_event(
    BudgetAdjustmentEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_classifier_config(
    ClassifierConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_impact_config(
    ImpactConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_impact_event(
    ImpactEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_telematics_config(
    TelematicsConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_trip_data_dart(
    TripDataDart? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_trip_location_dart(
    TripLocationDart? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_schedule_alarms_dart(
    ScheduleAlarmsDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_telematics_config(
    TelematicsConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tracking_mode_dart(
    TrackingModeDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transport_mode(TransportMode self, SseSerializer serializer);

  @protected
  void sse_encode_trip_data_dart(TripDataDart self, SseSerializer serializer);

  @protected
  void sse_encode_trip_location_dart(
    TripLocationDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_trip_waypoint_dart(
    TripWaypointDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryBudgetEngineDart(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerImpactDetectorDart(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTreeDart(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScheduleParserDart(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmartMotionCoordinatorDart(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTelematicsEngineDart(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransportModeClassifierDart(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTripManagerDart(
    int ptr,
  );
}
