// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Impact detector tuning.
class ImpactConfig {
  /// Enable vehicle crash detection.
  final bool enableCrash;

  /// Enable personal fall detection (best-effort; more false positives).
  final bool enableFall;

  /// Impact magnitude (g) for a crash candidate.
  final double crashGThreshold;

  /// Pre-impact speed (km/h) required to corroborate a crash.
  final double crashMinSpeedKmh;

  /// Impact magnitude (g) for a fall candidate.
  final double fallGThreshold;

  /// Countdown (ms) before a candidate auto-confirms.
  final PlatformInt64 confirmWindowMs;

  /// Suppress candidates below this confidence.
  final double minConfidence;

  const ImpactConfig({
    required this.enableCrash,
    required this.enableFall,
    required this.crashGThreshold,
    required this.crashMinSpeedKmh,
    required this.fallGThreshold,
    required this.confirmWindowMs,
    required this.minConfidence,
  });

  @override
  int get hashCode =>
      enableCrash.hashCode ^
      enableFall.hashCode ^
      crashGThreshold.hashCode ^
      crashMinSpeedKmh.hashCode ^
      fallGThreshold.hashCode ^
      confirmWindowMs.hashCode ^
      minConfidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImpactConfig &&
          runtimeType == other.runtimeType &&
          enableCrash == other.enableCrash &&
          enableFall == other.enableFall &&
          crashGThreshold == other.crashGThreshold &&
          crashMinSpeedKmh == other.crashMinSpeedKmh &&
          fallGThreshold == other.fallGThreshold &&
          confirmWindowMs == other.confirmWindowMs &&
          minConfidence == other.minConfidence;
}

/// An impact event.
class ImpactEvent {
  /// `potential_crash` | `crash` | `potential_fall` | `fall`.
  final String kind;

  /// Candidate id — pair `potential_*` with its later `confirm`/`cancel`.
  final PlatformInt64 id;

  /// 0–1 confidence.
  final double confidence;

  /// Peak magnitude (g) of the impact.
  final double peakG;

  /// Speed before impact (m/s).
  final double speedBefore;
  final double latitude;
  final double longitude;
  final PlatformInt64 timestampMs;

  /// For `potential_*`: epoch ms at which it auto-confirms unless cancelled.
  final PlatformInt64 confirmDeadlineMs;

  const ImpactEvent({
    required this.kind,
    required this.id,
    required this.confidence,
    required this.peakG,
    required this.speedBefore,
    required this.latitude,
    required this.longitude,
    required this.timestampMs,
    required this.confirmDeadlineMs,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      id.hashCode ^
      confidence.hashCode ^
      peakG.hashCode ^
      speedBefore.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      timestampMs.hashCode ^
      confirmDeadlineMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImpactEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          id == other.id &&
          confidence == other.confidence &&
          peakG == other.peakG &&
          speedBefore == other.speedBefore &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          timestampMs == other.timestampMs &&
          confirmDeadlineMs == other.confirmDeadlineMs;
}
