// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A detected driving event.
class DrivingEvent {
  /// `harsh_braking` | `harsh_acceleration` | `harsh_cornering` | `speeding`.
  final String kind;

  /// Normalized 0–1 severity (how far past the threshold).
  final double severity;

  /// Speed at the event (m/s).
  final double speed;

  /// The measured magnitude that triggered it: g for harsh events, km/h over
  /// the limit for speeding.
  final double value;
  final double latitude;
  final double longitude;
  final PlatformInt64 timestampMs;

  const DrivingEvent({
    required this.kind,
    required this.severity,
    required this.speed,
    required this.value,
    required this.latitude,
    required this.longitude,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      severity.hashCode ^
      speed.hashCode ^
      value.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrivingEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          severity == other.severity &&
          speed == other.speed &&
          value == other.value &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          timestampMs == other.timestampMs;
}

/// Tunable thresholds for driving-event detection. Defaults follow common
/// usage-based-insurance / fleet practice and are overridable by the caller.
class TelematicsConfig {
  /// Longitudinal deceleration (g) above which `harsh_braking` fires.
  final double harshBrakingG;

  /// Longitudinal acceleration (g) above which `harsh_acceleration` fires.
  final double harshAccelerationG;

  /// Lateral acceleration (g) above which `harsh_cornering` fires.
  final double harshCorneringG;

  /// Global speed limit in km/h. `0` disables threshold-based speeding
  /// (per-geofence limits can still be applied by the caller).
  final double speedLimitKmh;

  /// Grace (km/h) added to the limit before speeding counts.
  final double speedingToleranceKmh;

  /// Sustained time over the limit (ms) before `speeding` fires.
  final PlatformInt64 speedingMinDurationMs;

  /// Suppress brake/accel/corner events below this speed (km/h) to avoid
  /// parking-lot / GPS-jitter noise.
  final double minSpeedForEventsKmh;

  /// Minimum time between two events of the same kind (ms) — debounce so a
  /// single maneuver spanning several fixes yields one event.
  final PlatformInt64 eventDebounceMs;

  const TelematicsConfig({
    required this.harshBrakingG,
    required this.harshAccelerationG,
    required this.harshCorneringG,
    required this.speedLimitKmh,
    required this.speedingToleranceKmh,
    required this.speedingMinDurationMs,
    required this.minSpeedForEventsKmh,
    required this.eventDebounceMs,
  });

  @override
  int get hashCode =>
      harshBrakingG.hashCode ^
      harshAccelerationG.hashCode ^
      harshCorneringG.hashCode ^
      speedLimitKmh.hashCode ^
      speedingToleranceKmh.hashCode ^
      speedingMinDurationMs.hashCode ^
      minSpeedForEventsKmh.hashCode ^
      eventDebounceMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelematicsConfig &&
          runtimeType == other.runtimeType &&
          harshBrakingG == other.harshBrakingG &&
          harshAccelerationG == other.harshAccelerationG &&
          harshCorneringG == other.harshCorneringG &&
          speedLimitKmh == other.speedLimitKmh &&
          speedingToleranceKmh == other.speedingToleranceKmh &&
          speedingMinDurationMs == other.speedingMinDurationMs &&
          minSpeedForEventsKmh == other.minSpeedForEventsKmh &&
          eventDebounceMs == other.eventDebounceMs;
}
