// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Classifier tuning.
class ClassifierConfig {
  /// A candidate mode must persist this long (ms) before it commits.
  final PlatformInt64 modeSwitchDwellMs;

  /// Below this confidence the result is reported as `Unknown`.
  final double minConfidence;

  const ClassifierConfig({
    required this.modeSwitchDwellMs,
    required this.minConfidence,
  });

  @override
  int get hashCode => modeSwitchDwellMs.hashCode ^ minConfidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClassifierConfig &&
          runtimeType == other.runtimeType &&
          modeSwitchDwellMs == other.modeSwitchDwellMs &&
          minConfidence == other.minConfidence;
}

/// Result of a classification step.
class ModeResult {
  final TransportMode mode;
  final double confidence;

  /// True when this call committed a *change* from the previous committed mode.
  final bool changed;

  const ModeResult({
    required this.mode,
    required this.confidence,
    required this.changed,
  });

  @override
  int get hashCode => mode.hashCode ^ confidence.hashCode ^ changed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModeResult &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          confidence == other.confidence &&
          changed == other.changed;
}

/// Detected travel mode. Distinct from the platform `ActivityType` so adding
/// `Cycling` here doesn't perturb existing activity plumbing.
enum TransportMode { unknown, still, walking, running, cycling, vehicle }
